### ISSUE TITLE
Selecting the same item multiple times

### ISSUE THREAD

**Issue by ahwayakchih** [symphonists/subsectionmanager#117] opened 2011-05-21 18:16 UTC
I am going to work on feature to allow author to select item multiple times, and i was wondering what are the plans for SubsectionManager changes in near future.

Since my english is not good enough for me to explain ideas, here's example.

There are two sections: `Boxes` and `Items`. Each entry in `Boxes` section can have multiple `items` inside it (Boxes section has SubsectionManager field called `items` which points to `Items` section :). This is already possible with SubsectionManager.
Now i need to allow author to select the same Item multiple times, so there is no need for "bridge" section like `ItemInABox` (which would require creating entry for each item in a box, and make that entry point to entry in `Items` section).

I was planning to write extension that will add little "+" and "-" signs on each selected item on list, so author would just click them and set "quantity" of items. Problem is that separate field would need to do a lot of additional stuff just to let XSLT know which number is for which SubsectionManager field/item. Extension that modifies SubsectionManager table in database does not sound good either.

So i am wondering if there is a plan to allow for selecting the same entry multiple times? I've read that you plan to jump from using `select` to `input` - that would make implementing `quantity` thing very easy. Did you plan such feature? Would you accept patch that implements it (or helps implementing it through separate extension)?

**Comment by nilshoerrmann** [comment] 2011-05-21 18:59
I haven't thought of that usecase but that sounds like a nice addition. SSM 2.0 is supposed to introduce the switch from a select box to hidden inputs as storage. I'm developping this extension in my spare time so I cannot give you a date when this change will be ready.

**Comment by ahwayakchih** [comment] 2011-05-21 19:18
I can prepare patch if you think it's OK. It would implement switch from select to input, and then maybe add "quantity" in database table and option to "allow selecting the same entry multiple times" (or maybe better would be to write "force unique selection"?).

**Comment by nilshoerrmann** [comment] 2011-05-22 06:16
I think we need to discuss a few things first to make this work:
- Is this an additional Stage setting or a Subsection Manager feature only?
- Should items be visible multiple times or will there be a counter?
- How should it be visualised in the queue that quantites are enabled? Stage only knows two states: selected and not selected.

**Comment by ahwayakchih** [comment] 2011-05-22 07:00
> Is this an additional Stage setting or a Subsection Manager feature only?

I was thinking about SubsectionManager, but now i see it probably would be better on Stage side (internally) and then used by SubsectionManager.

> Should items be visible multiple times or will there be a counter?

I was planning to make it show counter, but Stage could show items multiple times, and then additional script could override it. I cannot think of a situation when showing item multiple times would be better, but that does not mean there is none. Any ideas?

> How should it be visualised in the queue that quantites are enabled? Stage only knows two states: selected and not selected.

So, to keep Stage simple (keep only two states), it could show item multiple times. Queue could have counter (and "+/-" buttons?). On the other hand, if there will be buttons in Queue, then Stage could show them too...
Maybe Stage should create multiple `li` elements for each item, but visually collapse them into one (with counter and buttons)?

**Comment by nilshoerrmann** [comment] 2011-05-22 08:05
> So, to keep Stage simple (keep only two states), it could show item multiple times. 

The problem is: deselecting an item in the queue removes it from the selection, selecting adds it again. How should this work with a "one to many clones" relationship?

> Queue could have counter (and "+/-" buttons?)

I'm not sure about adding `+` and `–` buttons – at least I think they should not be visible all the time as it would clutter the interface. And I not sure if the queue is the right place (we are talking about the list of all available items under the search bar): if I want to raise the quantity, why should I have to open the queue for that task and not use the selection list where my item is already present (in another quantity).

**Comment by ahwayakchih** [comment] 2011-05-22 08:19
> The problem is: deselecting an item in the queue removes it from the selection, selecting adds it again. How should this work with a "one to many clones" relationship?

Deselecting in Queue would deselect all "clones". Same as "destructor" button.

>  if I want to raise the quantity, why should I have to open the queue for that task and not use the selection list where my item is already present (in another quantity).

You are right. I was thinking about adding `+` and `-` buttons in both Queue and Selection, but that seems too much of a trouble (even if buttons will be visible only when mouse is over item). Buttons could be placed only on Selection items (and visible only when mouse pointer moves over item, counter part would be visible all the time, e.g., "[photo] Item A          x2 [X button]" and "[photo] Item A      +/- x2 [X button]" - notice buttons show up before counter - to prevent clicking [X] by accident :). Clicking on Queue item would either remove item from selection (all "copies" would be removed) or add to selection (if it was not selected before, quantity would be set to 1).

**Comment by nilshoerrmann** [comment] 2011-06-07 17:08
In my opinion this feature should be part of version 2. I created a new branch `multiple` that should be merged with the `2.x` branch later. I granted you push rights for this repository so please feel free to start with the implementation.

**Comment by ahwayakchih** [comment] 2011-06-07 21:28
OK, thanks :).

We're using 1.x in a project, so i think i will start experimenting on 1.x and then port it to 2.x.
Or can 2.x be used in a production environment? Is there much left to do, or just a few fixes?

**Comment by nilshoerrmann** [comment] 2011-06-08 05:33
I'm using version 2 for my projects and it's working really well. We still need to implement a different sorting logic but the current one is working of course. It should be much faster because it caches entries for data source output.

**Comment by ahwayakchih** [comment] 2011-06-08 10:00
OK, i will move to 2.x then. Is there anything i should be worry about when updating module from 1.x to 2.x?

**Comment by nilshoerrmann** [comment] 2011-06-08 10:02
Yes, the included elements are now stored in the data source directly so you will have to re-add all elements in the data source editor.

**Comment by ahwayakchih** [comment] 2011-06-08 10:11
But field settings will be left ok (so i can check what i needed and where :)? And i will just have to edit all data sources?

**Comment by nilshoerrmann** [comment] 2011-06-08 10:14
As long as you don't mess up your database, everything should be fine (field settings, selected items, sorting etc.). But as always: backup your system before updating :)

**Comment by ahwayakchih** [comment] 2011-06-08 10:15
OK, thanks :).

**Comment by nilshoerrmann** [comment] 2011-06-08 10:16
> And i will just have to edit all data sources?

Yes. Version 1 stores the included elements in the database. Version 2 uses the data source file (as it always should have - but it wasn't possible before the release of Symphony 2.2).

**Comment by ahwayakchih** [comment] 2011-06-08 10:19
Great, i like the idea of selecting included fields per data source too :).

**Comment by ahwayakchih** [comment] 2011-06-08 11:52
Hmm... "selected fields" setting is not shown on section edit page. I will have to rediscover all fields i use in all XSLT files and datasources. Would be great if there was some kind of helper that shows up which fields were selected before. Maybe JavaScript that highlights (selects) them on data source edit page (after a click on some button)?

Also:

> Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 86 bytes)

When trying to edit data source :(.

**Comment by ahwayakchih** [comment] 2011-06-08 12:12
It is the recursion thing again :(.

Also how will Reflection field work now? With 1.x it was getting the fields i selected on section edit page. How will it get them now?

**Comment by nilshoerrmann** [comment] 2011-06-08 12:15
I'm not sure, if I can follow.

**Comment by ahwayakchih** [comment] 2011-06-08 12:25
The helper part? I was thinking about JavaScript added to Data Source edit page. It would create small button, e.g., "Import from 1.x settings". Clicking on it would make SSM try to convert "selected fields" configured on section edit page, to list of fields needed to select on Data Source page and mark them as selected.

As for recursion part, i just created patch :).

Reflection field could access SSM objects. For example, imagine standard Photos and Articles sections. Articles section has SSM field called "Photos" and pointing to Photos section. On Articles section edit page i selected "Photos" to be included in XML. When Reflection field prepares XML, it calls fields to generate their XML part. So in the end, i could access list of Photos (their title, files, even SSM data if there was any and Photos section was configured to include it in XML, etc...) when generating value for Reflection field. How will it work now? Since there is no "default" data source configured, what should be done for Reflection field to access data of subsection fields?

**Comment by ahwayakchih** [comment] 2011-06-08 14:29
Sorry for posting off-topic stuff here. I created new issue for all that stuff: https://github.com/nilshoerrmann/subsectionmanager/issues/127

**Closed as completed** 2011-06-16 15:44 UTC
