### ISSUE TITLE
Sometimes doesn't expand to full height

### ISSUE THREAD

**Issue by DavidOliver** [symphonists/subsectionmanager#88] opened 2011-03-20 17:36 UTC
Sometimes SSM doesn't expand to its full height when creating a new entry which can mean some of the subsection's fields are hidden. This seems to happen on the initial attempt; if it's cancelled and tried again it does expand fully.

Version 1.1.1. Symphony 2.2.

Firefox 3.6, Ubuntu Linux 10.10.

**Comment by brendo** [comment] 2011-03-29 01:48
I can reproduce this, only every so often though.

Firefox 4, Mac OSX

**Comment by nilshoerrmann** [comment] 2011-04-07 13:31
Does this happen right after the parent entry has been loaded or spontaneous later on?

**Comment by liamegan** [comment] 2011-04-13 02:24
I have this same issue in both FF 3.6 and FF 4.0. It happens when creating new entries and when editing existing entries (although the behaviour is slightly different for each) see:

New entry:
http://cl.ly/0O3o3z350f1t1x3k2o47

Edit existing:
http://cl.ly/3P1N0l3Y0b1U3v053o2Y

**Comment by liamegan** [comment] 2011-04-13 02:47
It looks like this bug may have to do with the permissions system in Symphony 2.2. I haven't done any in-depth testing, but the above was happening only to Authors with limited access to the sections to which the subsection manager linked.

**Comment by nilshoerrmann** [comment] 2011-04-13 06:35
Thanks for the screenshot. I thought _that_ bug was fixed - hm. I'll check my development copy, maybe it's in the commits that have yet to be released.

> I haven't done any in-depth testing, but the above was happening only to Authors with limited access to the sections to which the subsection manager linked.

What are authors with "limited access"? Are you using Author Roles?

**Comment by jameswestnz** [comment] 2011-04-13 07:58
Hi Nils - same issue here - FF 3.6.
I'll try get a screenshot through tomorrow.

**Comment by DavidOliver** [comment] 2011-04-13 07:58
It's not limited to Authors - happens to me in my main Developer account.

**Comment by nilshoerrmann** [comment] 2011-04-13 09:29
Which version of SSM are you all using? Are you by any chance using Date and Time, too?

**Comment by DavidOliver** [comment] 2011-04-13 09:37
I'm not using Date and Time.

**Comment by nilshoerrmann** [comment] 2011-04-13 09:39
That's good, or bad - depending on the point of view. Are you able to actively reproduce the behaviour or is it just happening spontaneous?

**Comment by nilshoerrmann** [comment] 2011-04-13 09:41
If you're experiencing this issue, could you please be so kind and copy the _generated source_ of the SSM field to this thread (copy from Firebug or the Web Inspector to be sure all DOM changes are visible). Thanks!

**Comment by DavidOliver** [comment] 2011-04-13 09:52
I'm having trouble reproducing it now, but I've recorded a quick screencast which shows what may be a related issue: after opening the create new section and closing it, the currently selected items are clipped. This isn't the same as the create new fields being hidden (I couldn't get this to happen this morning), but thought it might be relevant.

http://vimeo.com/22333100 (still currently processing)

**Comment by jameswestnz** [comment] 2011-04-13 21:01
HTML output from firebug: http://pastie.org/1792882

I seem to get this issue every time - SSM is in main area, and is below the bottom of the screen as a result - so it could be a simple CSS fix?

**Comment by pixelninja** [comment] 2011-04-14 00:04
generated source code of SSM:
  http://pastie.org/1793443

screenshots:
  http://img710.imageshack.us/i/screenshot20110414at958.png/

  http://img718.imageshack.us/i/screenshot20110414at958.png/

Happens when saving or creating an entry.

**Comment by nilshoerrmann** [comment] 2011-04-14 06:27
Thanks for all the updates. I'll will have a look at it over the next days.

**Comment by nilshoerrmann** [comment] 2011-04-14 06:31
Just as an aid to memory, this issue could be related to:
- interfering Stage and SSM styles (`overflow`)
- problems with reading the `iframe` height (Firefox returns the default height, when the frame is hidden)
- an element mismatch, where Stage tries to add the drawer to the wrong parent
- a jQuery and/or Firefox bug

**Comment by nilshoerrmann** [comment] 2011-04-14 06:33
Two more questions:
- Are you running any Firefox Addons that interfere with the page source?
- Does this also happen when you disable Firebug?

**Comment by nilshoerrmann** [comment] 2011-04-14 09:06
Another question:
- Do you have a single or multiple instances of Subsection Manager in your section?

**Comment by pixelninja** [comment] 2011-04-14 13:23
I was running a few add ons. I disabled them all, including firebug, and tried again, but it still did the same thing.

And yea, I have a SSM field within a SSM field. 

I'm using Firefox 4. Works fine in Chrome.

**Comment by DavidOliver** [comment] 2011-04-14 13:30
My SSM is not within another SSM, and is the only SSM in the section.

**Comment by nilshoerrmann** [comment] 2011-04-14 13:34
Are you all using version 1.1.1 (`master`/`development` branch) or has anyone switched to one of the other branches?

**Comment by pixelninja** [comment] 2011-04-14 22:16
Yea I have 1.1.1 development checked out

**Comment by nilshoerrmann** [comment] 2011-04-19 08:15
I did a few tests, and I cannot reproduce this at all with the code in the `tabs` branch and Firefox 4 on Mac. Could someone be so kind and checkout that branch to see if this solves the issue? Beware that datasource output is broken in that branch.

Thanks!

**Comment by nilshoerrmann** [comment] 2011-04-19 08:30
Hm, maybe I found something: I have two development installs - one localised the other in English. It seems like the English one has some problems. I still cannot reproduce the behaviour described in this thread, but in the English version I see the editor jumping when creating a new item and I have a dubious `System` error note in Firebug. The only difference seems to be the fact that the English version didn't have to load translations for the core. It doesn't make much sense.

**Comment by nilshoerrmann** [comment] 2011-04-19 08:44
Okay, this is just a guess. Could you please replace the [create function](https://github.com/nilshoerrmann/subsectionmanager/blob/development/assets/subsectionmanager.publish.js#L286-301) in `subsectionmanager.publish.js` with the following and report back if this changes anything for you? Thanks!

```
// Create item
var create = function(item) {
    stage.trigger('createstart', [item]);

    var editor = drawer.clone().hide().addClass('new');

    // Prepare iframe
    editor.find('iframe').css({
        'opacity': 0.01,
        'height': 0                 
    }).attr('src', subsection_link + '/new/').load(function() {
        iframe = $(this);
        load(item, editor, iframe);
    });

    // Show subsection editor
    editor.insertAfter(item).slideDown('fast');         

    stage.trigger('createstop', [item]);
};
```

**Comment by nilshoerrmann** [comment] 2011-04-26 06:30
Please checkout https://github.com/nilshoerrmann/subsectionmanager/tree/1.2beta

**Comment by nilshoerrmann** [comment] 2011-05-04 08:36
I take the silence as confirmation. Closing this issue.

**Closed as completed by nilshoerrmann** 2011-05-04 08:36 UTC
