### ISSUE TITLE
Entries don't show up in XML

### ISSUE THREAD

**Issue by r00dY** [symphonists/subsectionmanager#111] opened 2011-05-08 18:29 UTC
I'm using Symphony 2.2.1 and a newest version of Subsection Manager. When I add a new entry via Subsection Manager and save changes in a parent entry, the fresh entry shows up in a SM, it shows up in a database, but it doesn't show up in an XML file when I reload my webpage. I need to sort any elements in SM to get a newly created entry in a XML. This is so sad :(

**Comment by nilshoerrmann** [comment] 2011-05-09 05:21
- Which exact version are you using?
- How did you set up your field?
- How did you set up your data source
- Do you see anything in the XML at all?

**Comment by ahwayakchih** [comment] 2011-05-09 07:08
I did not test latest code yet, but version 1.1.1 does not set sortorder for new items. Maybe that is the reason of them not showing up in XML?

**Comment by r00dY** [comment] 2011-05-10 09:14
SM version 1.1.1
My setup: allow creation, allow sorting, allow deselection, allow selection of multiple. The only difference from default settings is that I turned off "allow selection from the list of existing items".
Datasource is ususal, I have subsection manager selected in "Included elements".

I see all XML well! The only problem is that when I add a new element via SM then this new element doesn't show up as a new item in subsection manager tag. Only after sorting it works. Funny thing is that in one instance of SM it happens, in other, it doesn't!

Nils, I could give you the access to this CMS, you could take a look then. Are you intrested? :)

**Comment by nilshoerrmann** [comment] 2011-05-10 09:21
Thanks for the update. It seems to be the old sorting bug which will definitely be solved in SSM 2.0 but I will need to find a quick fix for the upcoming release of SSM 1.2.

> Nils, I could give you the access to this CMS, you could take a look then. Are you intrested? :)

I'll see if I can reproduce the issue on my development copy and will contact you if I cannot. Thanks!

**Comment by ahwayakchih** [comment] 2011-05-10 14:42
Nils, i noticed that:

```
            var sortorder = selection.find('li').map(function() {
                return $(this).attr('data-value');
            }).get().join(',');
```

will not return new items, even if it is run right after items were added and `stage.trigger('edit')` was called for each of them. I had to add new items to sortorder "manually" (in my function, code knows which new items were added, so it injects them into sortorder). Can that be somehow connected to this problem?

**Comment by nilshoerrmann** [comment] 2011-05-10 16:38
That shouldn't be a problem. The real issue lies in the data source output function which should simply add "unsorted" aka new items at the end of the XML. For some reason it doesn't.

**Comment by ahwayakchih** [comment] 2011-05-10 17:37
>  The real issue lies in the data source output function which should simply add "unsorted" aka new items at the end of the XML. For some reason it doesn't.

That's probably because `field.subsectionmanager.php` in its `appendFormattedElement` function appends only those entries that are found in sortorder. Sortorder does not contain new items, hence they are not added to XML.

Look at the line [#689](https://github.com/nilshoerrmann/subsectionmanager/blob/merging/fields/field.subsectionmanager.php#L689). Code there looks like this:

```
        $sorted_entries = array();
        if(!empty($sorted_ids) && $sorted_ids[0] != 0 && !empty($sorted_ids[0])) {
            foreach($sorted_ids as $id) {
                foreach($entries as $entry) {
                    if($entry->get('id') == $id) {
                        $sorted_entries[] = $entry;
                    }
                }
            }
        }
        else {
            $sorted_entries = $entries;
        }

        // Build XML
        $count = 1;
        foreach($sorted_entries as $entry) {
            // [...]
        }

        // Append Subsection Manager to data source
        $wrapper->appendChild($subsectionmanager);
```

If entry was saved before (and user selected at least one item in SubsectionManager field), code above will loop through `$sorted_ids`, and "select" only those entries that are found both in `$sorted_ids` and `$entries` arrays (basically it tries to get IDs of entries in sorted order, but without those removed after `sortorder` was saved to database). It "forgets" about any other `$entry` that was selected by user, but was not sorted.

That is why [Bulk Importer](https://github.com/brendo/bulkimporter/blob/integration/assets/bulkimporter.publish.js#L124) adds new items to sortorder field. They are added at the end of list (as "last" items), so order of other items is not changed (result is the same as if they were not sorted at all, only they do show up in XML :).

**Comment by nilshoerrmann** [comment] 2011-05-10 17:41
Yes, I know - the thing is that there once was code to add the "unsorted" items at the end of the XML and I don't know what happened to that code :)

**Comment by ahwayakchih** [comment] 2011-05-10 18:11
You probably had it in local version somewhere and never commited it :(.

Maybe it would be good idea to change sorting part of the function and get entries from database already sorted out? With sort order stored like it is now, it seems to be a perfect place to use MySQL's [FIELD()](http://dev.mysql.com/doc/refman/5.0/en/string-functions.html#function_field) function ([example](http://lists.mysql.com/mysql/209784)).

**Comment by nilshoerrmann** [comment] 2011-05-10 18:15
See https://github.com/nilshoerrmann/subsectionmanager/issues/86

**Comment by ahwayakchih** [comment] 2011-05-10 20:12
Well... if sort order will not be kept separate in future, then following code probably will not be needed, but maybe you will find it useful for now. 

Declare `static $sortOrder = NULL;` in `fieldSubsectionmanager` class and add following function to it:

```
    public function buildSortingSQL(&$joins, &$where, &$sort, $order='ASC'){
        $entry_id = self::$sortOrder;
        self::$sortOrder = NULL;
        if (empty($entry_id)) return;

        // Get sort order for entries
        $order = Symphony::Database()->fetchVar('order', 0,
            "SELECT `order`
            FROM `tbl_fields_stage_sorting`
            WHERE `entry_id` = " . intval($entry_id) . "
            AND `field_id` = " . $this->get('id') . "
            LIMIT 1"
        );

        if (empty($order)) {
            $sort = 'ORDER BY `e`.`id` ASC';
        }
        else {
            // We could validate $order to be sure all values are integers,
            // but it always is validated before being saved to database.
            // Reverse order because FIELD() returns 0 for "not found".
            // So if order is "A,B,C,D", not found will be before them :(.
            $order = implode(',', array_reverse(explode(',', $order)));
            $sort = 'ORDER BY FIELD(`e`.`id`,'.$order.') DESC';
        }
    }
```

After that, change `appendFormattedElement` function so instead of:

```
        // Fetch field data
        $entryManager = new EntryManager(Symphony::Engine());
        $entries = $entryManager->fetch($data['relation_id'], $this->get('subsection_id'));

        // Sort entries
        $order = Symphony::Database()->fetchVar('order', 0,
            "SELECT `order`
            FROM `tbl_fields_stage_sorting`
            WHERE `entry_id` = " . $wrapper->getAttribute('id') . "
            AND `field_id` = " . $this->get('id') . "
            LIMIT 1"
        );
        $sorted_ids = explode(',', $order);
        $sorted_entries = array();
        if(!empty($sorted_ids) && $sorted_ids[0] != 0 && !empty($sorted_ids[0])) {
            foreach($sorted_ids as $id) {
                foreach($entries as $entry) {
                    if($entry->get('id') == $id) {
                        $sorted_entries[] = $entry;
                    }
                }
            }
        }
        else {
            $sorted_entries = $entries;
        }
```

There is:

```
        // Fetch field data
        $entryManager = new EntryManager(Symphony::Engine());
        $entryManager->setFetchSortingField($this->get('id'));

        // EntryManager checks for known directions so we had to workaround that by using static variable.
        // $entryManager->setFetchSortingDirection('SSM:'.$wrapper->getAttribute('id'));
        self::$sortOrder = $wrapper->getAttribute('id');

        $sorted_entries = $entryManager->fetch($data['relation_id'], $this->get('subsection_id'));
```

I just tested it quickly (so more testing may be needed) and it executes a bit faster while returning all entries in XML (after ten reloads, average for code before change was: 6 entries in 0.021090139 seconds, and after change was: 7 entries in 0.018199552 seconds :).
It probably would execute even faster if sortorder was stored in database in reversed order.

**Comment by ahwayakchih** [comment] 2011-05-12 17:35
Fixed bug in code posted above.

**Comment by nilshoerrmann** [comment] 2011-06-07 12:39
This should be fixed with Marcin's commits. Thanks!

**Closed as completed by nilshoerrmann** 2011-06-07 12:39 UTC
