### ISSUE TITLE
Dragging and dropping to textarea keeps reordering items

### ISSUE THREAD

**Issue by ahwayakchih** [symphonists/subsectionmanager#96] opened 2011-04-08 10:59 UTC
Tested in Chrome (Chromium) 12.0.729.0.

When i try to drag and drop item to textarea, it keeps getting reordered if drop point is placed higher or lower than X,Y position of item in Subsection Manager field.

I understand that setting up separate areas to start dragging from may be wrong (too complicated to use), but maybe reordering could be canceled once item is dropped to textarea? And/Or while mouse pointer is over textarea, reordering could be cancelled and stopped?

**Comment by nilshoerrmann** [comment] 2011-04-08 11:04
I know this is a bit odd but the problem is that until the mouse pointer leaves the Subsection Manager field you don't know if the user is reordering or dragging. So far I haven't found a way to cancel the reordering on dragging. Any ideas?

PS: It would be possible to store the sort order before dragging using `localStorage` and restore it when it's clear that the user is dragging and not sorting. But in my opinion it gets confusing for the user as the interface will "flip around" when this restoring process takes place.

**Comment by ahwayakchih** [comment] 2011-04-08 11:17
Maybe reorder only if mouse pointer is "in area" of Subsection Manager field? "In area" could be exact area or area + 10px around it. Movement out of area would not reorder, but moving mouse back to area would continue reordering.

**Comment by nilshoerrmann** [comment] 2011-04-08 11:39
Hm, I'm not sure if I'm following. This is how SSM currently works:
- As long as the user is inside the fields dimensions plus 10px around it, it will reorder items.
- If the user leaves this area, the item will be dragged outside the list.
- If the user wants to drag but - in order to move outside the list - reorders first, the item will be sorted and dragged.

The problem is that you don't want to have an item sorted when it is dragged and this cannot be achieved easily:
- You cannot wait for a "drag out" before starting to sort because this will break sorting completely.
- As I said above it would be possible to restore the initial sort order if the user decides to drag and item out. But this will flip the sort order abruptly and will create a confusing user experience in my eyes.

The main problem lies in the way Symphony displays sorting: the items are sorted directly and not with the help of a half transparent duplicate like in most operating systems. But dragging and sorting are actually to flavours of the same process: the one is an internal the other and external dragging. Symphony's core doesn't take dragging into account which is the main source oft the strange mixture of behaviours as the visual look of Symphony's sorting process cannot be used for dragging as well.

I think there will be no satisfying solution until Symphony's sorting will be rethought as a dragging process.

**Comment by ahwayakchih** [comment] 2011-04-08 11:57
This is how i tested it:
1. Click on few items to select them (to have more than one item selected).
2. Click on selected item that is last in order from top to bottom (so item at the bottom of selected items) and move mouse pointer out of Subsection Manager field area while keeping mouse button pressed.
3. Move mouse pointer horizontally so it does not change order of selected items.
4. Drag item over textarea and move mouse pointer vertically too (textarea could be placed above Subsection Manager field).
5. Drop item.

Following those steps will drop text into textarea but also reorder items.

Reorder process/handling should stop at step 3.

I thought that it is Subsection Manager that handles drag and drop processing, but if it depends on Symphony, then it might be a problem with Symphony JavaScript instead.

**Comment by nilshoerrmann** [comment] 2011-04-08 12:19
Ah, now I see. Thanks for clarifying. Hm, maybe we can do something about that ...

> I thought that it is Subsection Manager that handles drag and drop processing, but if it depends on Symphony, then it might be a problem with Symphony JavaScript instead.

Symphony takes care of the sorting and Subsection Manager hooks into that process to add the drag and drop feature. Symphony's JavaScript works fine - at least for Symphony's core. But the sorting concept was laid out without dragging in mind. It. is. quite. complicated. :)

**Comment by ahwayakchih** [comment] 2011-04-08 12:33
> Hm, maybe we can do something about that ...

It would be great :).

> But the sorting concept was laid out without dragging in mind. It. is. quite. complicated. :)

Hehe :).
Maybe it still would be a good idea to add area checking to it? I know it is easier to sort items by moving mouse pointer carelessly, but restricting area a little bit shouldn't make end users go all mad :).

**Comment by nilshoerrmann** [comment] 2011-04-08 12:38
The area check is already in the SSM codebase - it's used to trigger the dragging event. The only problem is that the sorting event needs to be unbound when the cursor leaves this zone and needs to be rebound when the cursors moves back in again while keeping the selected item the same. Not sure if it's possible with the current `symphony.orderable.js` plugin. We'll see.

**Comment by ahwayakchih** [comment] 2011-04-08 12:53
I looked into `symphony.orderable.js` quickly, so i may be totally wrong here, but maybe removing and adding `.orderable` class (inside SSM JavaScript) from item could stop/start ordering process?

**Comment by nilshoerrmann** [comment] 2011-04-08 12:56
No, I don't think so: the class is only used on `.ready()` to apply the sort functionality.

**Comment by ahwayakchih** [comment] 2011-04-10 13:21
I tried to hijack setup, and managed to prevent reordering outside of field by setting another mousemove delegate before Symphony will sets its own. It prevents Symphony from getting mousemove event when mouse pointer is outside of field area. Problem is that it also prevents SSM from handling drag and drop at the same time (looks like it depends on Symphony handling of mousemove event?).

```
var symphonyOrderable = $.fn.symphonyOrderable;
$.fn.symphonyOrderable = function(custom_settings) {
    var settings = {
        items:              'li',
        handles:            '*',
        delay_initialize:   false
    };
    $.extend(settings, custom_settings);
    console.log('hijacked symphonyOrderable!');
    if ($(this).parent().is('.draggable') && $(this).parents('div.field-subsectionmanager').length > 0) {
        this.map(function(){
            $(this).delegate(settings.items + ' ' + settings.handles, 'mousedown.orderable', function(event) {
                // Keep fields accessible inside orderable list
                if(!$(event.target).is('input, textarea, select')) {
                    var area = $(this).parents('div.field-subsectionmanager');
                    $(document).bind('mousemove.orderable', function(event){
                        var left = event.pageX,
                            offset = area.offset();
                        if (left < offset.left || left > (offset.left + area.width())) {
                            event.stopImmediatePropagation();
                            return false;
                        }
                    });
                    return false;
                }
            });
        });
    }
    return symphonyOrderable.call(this, custom_settings);
}
```

**Comment by nilshoerrmann** [comment] 2011-12-15 11:16
This has been fixed in Stage.

**Closed as completed by nilshoerrmann** 2011-12-15 11:16 UTC
Labels: confirmed
